# Generated by Django 3.1.1 on 2020-10-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201015_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.IntegerField(default='', max_length=40)),
                ('phone', models.CharField(default='', max_length=12)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
    ]
